### ISSUE TITLE
PDM can't load the plugin

### ISSUE THREAD

**Issue by pawamoy** [carstencodes/pdm-sbom#1]
```console
% pdm sbom -h               
WARNING: Failed to load plugin pdm-sbom=pdm_sbom:main: No module named 'packageurl'
Usage: pdm [-h] [-V] [-c CONFIG] [-v | -q] [-I] [--pep582 [SHELL]] ...
pdm: error: Script unknown: sbom
```

Looks like it's an issue with your [entry point](https://github.com/carstencodes/pdm-sbom/blob/main/pyproject.toml#L49), which doesn't exist?

**Comment by carstencodes** [comment]
The entrypoint [exists](https://github.com/carstencodes/pdm-sbom/blob/f6a6318a3cda2c37522141d1a079b8ef76c1491b/src/pdm_sbom/__init__.py#L14).

I have found the issue.
To minimize the dependency tree, the parts have been moved to extras. PURL were only used in SPDX and CycloneDX so far, but have now emerged to the core model.

As a workaround, I would suggest to use `pdm-sbom[spdx]` or `pdm-sbom[cyclonedx]` for installation.

I will provide an update in the course of the week.

**Comment by pawamoy** [comment]
Ah, I missed it, sorry.

I see, thanks for your help!

**Comment by carstencodes** [comment]
Sorry for the late reply. New Version is published, I uploaded the fix, but did Not publish the wheel.

Should Work now
